package org.example.model;

public enum BuildingEnum {
    SMALL_STONE_WALL,
    BIG_STONE_WALL,
    SMALL_STONE_GATEHOUSE,
    LARGE_STONE_GATEHOUSE,
    DRAW_BRIDGE,
    LOOKOUT_TOWER,
    PERIMETER_TOWER,
    DEFENCE_TURRET,
    SQUARE_TOWER,
    ROUND_TOWER,
    ARMOURY,
    BARRACKS,
    MERCENARY_POST,
    ENGINEER_GUILD,
    KILLING_PIT,
    OIL_SMELTER,
    PITCH_DITCH,
    CAGED_WAR_DOGS,
    SIEGE_TENT,
    STABLE,
    TUNNELER_GUILD,
    APPLE_ORCHARD,
    DIARY_FARMER,
    HOPS_FARMER,
    HUNTER_POST,
    WHEAT_FARM,
    BAKERY,
    BREWER,
    GRANARY,
    INN,
    MILL,
    IRON_MINE,
    MARKET,
    OX_TETHER,
    PITCH_RIG,
    QUARRY,
    STOCKPILE,
    WOODCUTTER,
    APOTHECARY,
    HOVEL,
    CHAPEL,
    CHURCH,
    CATHEDRAL,
    WELL,
    WATER_POT,
    GOOD_THINGS,
    BAD_THINGS,
    ARMOURER,
    BLACKSMITH,
    FLETCHER,
    POLE_TURNER,
    SIGNPOST,
    TUNNEL_ENTRANCE,


    // TREES


    DESERT_TREE,
    OLIVE_TREE,
    DATE_TREE,
    CHERRY_TREE,
    COCONUT_TREE,


    // ROCKS


    ROCK_NORTH,
    ROCK_SOUTH,
    ROCK_EAST,
    ROCK_WEST

}
